---
strict: true
site_name: mappers
site_description: |
  Declarative mappers from ORM models to domain entities. And back
  again!
theme:
  name: "material"
  palette:
    primary: "white"
    accent: "light-blue"
  logo: "https://raw.githubusercontent.com\
    /dry-python/brand/master/logo/dry-python.png"
  favicon: "https://raw.githubusercontent.com\
    /dry-python/brand/master/logo/dry-python.ico"
  language: "en"
  features:
    - tabs
repo_name: dry-python/mappers
repo_url: "https://github.com/dry-python/mappers"
edit_uri: ""
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
extra_javascript:
  - "javascripts/extra.js"
nav:
  - "Home":
      - "Home": index.md
      - "Changelog": changelog.md
